### ISSUE TITLE
2022-7 corner cases

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-device-connection-management#109]
We have trouble understanding how Nodes and Clients should behave in some 2022-7 "corner cases".

There was a discussion (#68) about a mismatch of the amount of legs in a `PATCH` request. The conclusion of that discussion was, a `PATCH` must always contain the exact amount of legs as announced on the `/constraints` endpoint.

This means, it is not directly possible to `PATCH` the `transport_params` of a 1-legged sender onto a 2-legged receiver without modification. The Client must manually add a second empty object to the `transport_params` to make it a valid request.

On the other hand, in the [4.1. Behaviour - RTP Transport Type document](https://amwa-tv.github.io/nmos-device-connection-management/tags/v1.1/docs/4.1._Behaviour_-_RTP_Transport_Type.html#operation-with-smpte-2022-7) the following is stated:

> Where a Receiver supports SMPTE 2022-7 but is required to receive a non-SMPTE 2022-7 stream, only the first set of transport parameters should be used. rtp_enabled in the second set of parameters must be set to false and transport parameters in the SDP file should be mapped onto that first set of parameters in the array.
> 
> Where a Receiver does not support SMPTE 2022-7 but receives a SMPTE 2022-7 transport file containing two sets of transport parameters it is recommended that it parses the first set of transport parameters found in the file and joins the stream as if it were a non-SMPTE 2022-7 stream. This ensures compatibility with Senders which do not support operation in a non-SMPTE 2022-7 mode.

The quoted text makes the assumption, that for example a 2-legged receiver receives a `PATCH` with only 1 leg, therefore he should just `rtp_enable=false` his second, unused leg. The other case is, that a receiver receives a `PATCH` containing `transport_params` for 2 legs, but only supports 1, therefore he should neglect the second leg.

Regarding the discussion in #68 and it's changes on the spec, the conditions described in the quote are invalid.

Where should the logic reside? 
Should the Client take care of the different amount of legs or should the Node act intelligent and take care of this mismatch.

Best what I can read from the current intersection of the specs & the schema is the following:
- a `PATCH` containing a different amount of legs compared to the 'to-be-patched' transceiver should be discarded by the Node
- the Client should take care of differences in these cases by adding empty objects (`{}`) in the `transport_params` array.*

(*) In some cases even more: if we want to `PATCH` a one-legged sender onto a receiver who currently has 2 active legs, the Client must even include a `rtp_enabled=false` in the missing leg to prevent having a receiver in a complete messed up state.

**Comment by garethsb** [comment]
> The quoted text makes the assumption, that for example a 2-legged receiver receives a PATCH with only 1 leg, therefore he should just rtp_enable=false his second, unused leg. 

Actually I think the quoted text refers to what the client should do?

In summary:
* In the case of `transport_params`, the client must match its request to the Receiver.
* In the case of `transport_file`, the Receiver must deal with it intelligently.

**Comment by jasperpeeters** [comment]
Now you say it, I can read it of the point of view of a Controller, but passages like this made me think it was of the point of a Node:

> [...] rtp_enabled in the second set of parameters must be set to false and transport parameters in the SDP file should be mapped onto that first set of parameters in the array.

Especially because in the next sentence this is stated (which is now really of the point of view of a Node):

> Where a Receiver [...] it is recommended that it parses the first set of transport parameters found in the file and joins the stream as if [...]

This can be easily misread in my eyes..

Is there a reason to split this logic on the Node and the Controller? If a Node can handle a mismatch in a `transport_file` it could also do this for a mismatch in `transport_params`?

**Comment by duncan-webb** [comment]
In the case where a single leg (non-2022-7 receiver) receives a /single/receivers/{receiverId}/staged REST call containing an SDP with two flows and a two sets of transport_params currently this is being rejected as a bad request (400) in nmos-cpp. If I understand you Gareth is it your understanding that it's the client's responsibility to send a transport_params array suitable for the receiver?

**Comment by garethsb** [comment]
Yes

**Comment by garethsb** [comment]
Hi Jasper,

I've been thinking about this, and why the unevenness in the spec between the transport parameters and the transport file exists.

I think the factors that led to the current spec are:
* Controllers necessarily _have to_ manipulate the JSON `transport_params`, they cannot just copy them from a Sender to a Receiver - e.g. in the case of RTP, Sender `"destination_ip"` needs to be used to set Receiver `"multicast_ip"` _and_ `"interface_ip"` (and a similar situation exists in the MQTT transport params)
* Node RTP Receivers necessarily _have to_ be able to parse and interpret the SDP file to extract the media parameters

The first point means that additionally getting the number of legs right should be low overhead for the Controller. The second point means that it is likely lower overhead in general for Nodes to handle a wider range of SDP files, than to require that all Controllers can parse and re-write SDP files.

**Comment by jasperpeeters** [comment]
Thanks @garethsb-sony for the clarification and explaining why the spec is like it is. Makes sense.

**Comment by garethsb** [comment]
Let's try to work out what tweaks to docs and/or test cases would clarify this for everyone's benefit!

**Comment by grmph555** [comment]
i would go for:

Where a Receiver supports SMPTE 2022-7 but is required to receive a non-SMPTE 2022-7 stream, **a controller shall send as many sets of transport_params as the constraints endpoint of the receiver is defining, but** only the first set of transport_params is containing a **non-empty array**. rtp_enabled in the **n+1** set of parameters must be set to false by the receiver. **It is expected that the receiver handles a transportfile containing multiple media descriptions (m=) in a way that it parses only the first set of parameters **

**Comment by garethsb** [comment]
> Where a Receiver supports SMPTE 2022-7 but is required to receive a non-SMPTE 2022-7 stream, *a controller shall send as many sets of transport_params as the constraints endpoint of the receiver is defining,*

I agree.

> *but* only the first set of transport_params is containing a *non-empty array.*

I think that would be a change in spec.

> rtp_enabled in the n+1 set of parameters must be set to false by the receiver.

As would that.

> **It is expected that the receiver handles a transportfile containing multiple media descriptions (m=) in a way that it parses only the first set of parameters **

And I think that's already covered?

**Comment by grmph555** [comment]
Where a Receiver does not support SMPTE 2022-7 but receives a SMPTE 2022-7 transport file containing two sets of transport parameters it is recommended that it parses the first set of transport parameters found in the file and joins the stream as if it were a non-SMPTE 2022-7 stream. This ensures compatibility with Senders which do not support operation in a non-SMPTE 2022-7 mode. The Controller needs to ensure that the transport_parameters match the receivers constraints.

**Comment by garethsb** [comment]
Expanding slightly on that, let's look at both paragraphs. Are the following tweaks too verbose?

Where a Receiver supports SMPTE 2022-7 but **receives a non-SMPTE 2022-7 transport file, the Receiver should set** `rtp_enabled` in the second set of parameters to false and transport parameters in the SDP file should be mapped onto that first set of parameters in the array.

**Where a Controller directly sets `transport_params` to configure such a Receiver for a non-SMPTE 2022-7 stream, it should set `rtp_enabled` in the second set of parameters to false.**

Where a Receiver does not support SMPTE 2022-7 but receives a SMPTE 2022-7 transport file containing two sets of transport parameters it is recommended that it parses the first set of transport parameters found in the file and joins the stream as if it were a non-SMPTE 2022-7 stream. This ensures compatibility with Senders which do not support operation in a non-SMPTE 2022-7 mode.

**In all cases, the Controller needs to ensure that the `transport_params` match the receiver's constraints.**

**Comment by grmph555** [comment]
I think they make sense. It does not sound too verbose to me!

**Comment by jasperpeeters** [comment]
Just as an additional note: we should be careful with wordings like first and second leg, as 2022-7 in it's latest versions talks about _n_ legs, not explicitly 2 anymore.

**Comment by a1800bert** [comment]
I agree, this "change" suggested by Gareth is more than important, from my point of view. Cause it clarify the relation between node-constraints and controller behaviour. A node should expect BOTH leg being set in a transport_params when it's contraints indicates two-leg. And same apply on the one leg.

If a node-constraints indicate 1-leg, than the controller SHOULD NOT send a two-leg transport_params.

**Comment by garethsb** [comment]
From Slack chat in which we discussed this issue:

* A Sender that supports ST 2022-7 (i.e. has two legs in **/constraints** and in `transport_params`) should (must) have two legs (two media descriptions) in its SDP file. _(Perhaps, replace 'two' with 'N'...)_

Additionally, some discussion about how `"rtp_enabled": false` might be reflected in the SDP file. One suggestion:

* If a Sender supports `a=inactive`, it could add/remove that attribute when `rtp_enabled` was toggled.
* If a Receiver supports `a=inactive`, it could set `rtp_enabled`  based on `a=inactive`, if not overridden by `rtp_enabled` being patched explicitly in the same or subsequent request.

However, in the case of a Controller that *only* transfers SDP files from Senders to Receivers, and then expects to be able to just change Sender `master_enable` and `rtp_enabled` to stop/start the stream, that wouldn't work.
