### ISSUE TITLE
/single/senders/{id}/staged describes behaviour of /transportfile. Why?

### ISSUE THREAD

**Issue by s13n** [AMWA-TV/nmos-device-connection-management#110]
The description for `/single/senders/{id}/staged` GET leaves me puzzled. It recommends to return 404 for a GET request to `/transportfile`, which "lives" elsewhere, when `master_enable` isn't true.

Firstly, I don't see why 404 should be returned at all in this case. Why should one not be able to read the transportfile when `master_enable` is false? I'd say it is both simpler and easier to understand when there's no such dependency.

Secondly, there's no mentioning of `master_enable` in the description of `/transportfile`, so I come to think that the inconsistency may be the result of an oversight.

**Comment by garethsb** [comment]
When a Sender is disabled or not fully configured, it may not be possible to generate a valid transport file. Therefore 404 is recommended from **/transportfile** when `"master_enable": false`. The wording in the description of **404** for **/transportfile** is "not currently configured".

**Comment by s13n** [comment]
That's fair enough, but in this case I would have expected wording like "When a valid transport file isn't available while a sender is disabled, a get request on /transportfile may return 404."

The way it is worded right now means that one should return 404 even when a valid transport file is available. That appears odd to me.

**Comment by garethsb** [comment]
I agree. There are very many **SHOULDs** in the specs that would have been better for interoperability as **MUSTs**, but this is one place where **MAY** seems reasonable. For what it's worth, I don't believe the IS-05 test suite reports if the recommendation isn't followed?

**Comment by s13n** [comment]
I haven't tried yet, But nmos-cpp does follow it. That's how I noticed.

**Comment by garethsb** [comment]
**nmos-cpp** tries to follow the specs ;-)

**Comment by s13n** [comment]
That's why I criticise the spec rather than nmos-cpp. ;-)
