### ISSUE TITLE
Do the API needs to validate the values with the constraints in the "GET" method of the "Staged" Endpoint?

### ISSUE THREAD

**Issue by vicabhu** [AMWA-TV/nmos-device-connection-management#129]
Hi.

Under the method description, what exactly does the "Additionally constrained by the constraints at /constraints" mean?

Does the API need to validate the values again? Since the constraints validation took place in the "PATCH" method only valid values are "staged" at this point (or am I missing something here?).

Thanks in advance.

Victor.

**Comment by garethsb** [comment]
For context, that note is on both the `/staged` endpoints' `GET` responses.
Once all values have been `PATCH`ed, what Victor says is true. I suspect the statement is made here to explain that even the initial values on device start-up are also constrained by the `/constraints`.

**Comment by vicabhu** [comment]
Thank you!
