### ISSUE TITLE
JSON Schemas link for release v1.1 yields Forbidden

### ISSUE THREAD

**Issue by rezonant** [AMWA-TV/nmos-device-connection-management#130]
The JSON Schemas link found at https://specs.amwa.tv/is-05/ fails with 403 Forbidden. The link is:
https://specs.amwa.tv/is-05/releases/v1.1/APIs/schemas/with-refs/

**Comment by garethsb** [comment]
Which page or menu linked to that URL? I think links should go to https://specs.amwa.tv/is-05/releases/v1.1/APIs/schemas/. Perhaps this was temporary and fixed already, @peterbrightwell?

**Comment by rezonant** [comment]
The link is "[JSON Schemas](https://specs.amwa.tv/is-05/releases/v1.1/APIs/schemas/with-refs/) for release v1.1" found on https://specs.amwa.tv/is-05/

![image](https://user-images.githubusercontent.com/409140/116165569-03e9ac80-a6b1-11eb-9714-b1582367ccdf.png)

It is still 403 Forbidden for me at https://specs.amwa.tv/is-05/releases/v1.1/APIs/schemas/with-refs/

The alternative link you mention (`https://specs.amwa.tv/is-05/releases/v1.1/APIs/schemas/`) works!

**Comment by garethsb** [comment]
Confirmed, thanks! The link on https://specs.amwa.tv/is-05/ gives 403, even though "the same" link on https://specs.amwa.tv/is-05/v1.1/ doesn't. (And same on other IS.)

Investigating!

**Comment by peterbrightwell** [comment]
See https://github.com/AMWA-TV/nmos-doc-build-scripts/pull/34

**Comment by peterbrightwell** [comment]
This should be fixed by https://github.com/AMWA-TV/nmos-doc-build-scripts/pull/34. This spec re-rendered and issues checked. Other specs require rebuild.
