### ISSUE TITLE
Nanoseconds vs ticks.

### ISSUE THREAD

**Issue by ghost** [AMWA-TV/nmos-device-connection-management#131]
Hello.

I am implementing the IS-05 in .NET (C#), here the smallest unit of time is the tick (which is equal to 100 nanoseconds).

It is clear to me that in NMOS the base unit is the nanoseconds since this is how the versions and activations  ("activate_scheduled_absolute" and "activate_scheduled_relative") are based.

What can I do in this case? Is it mandatory to have a base unit of nanoseconds?

Thanks in advance.

Victor.

**Comment by ghost** [comment]
Cool, Thanks!

**Comment by ghost** [comment]
Hello.

Back on topic. 

What exactly do you mean by "QoI issue"? What is "Qol"?

About the scheduled activations:

The time stamp given in "requested_time" is based on nanoseconds.

Does the specification then require nanosecond precision to perform the activation? Or what exactly does the specification say? I can't find it.

I know that there is already an issue about it (you mentioned it above) I just want to know what the specification says.

Thanks in advance.

Victor

**Comment by garethsb** [comment]
The accuracy of the activation is, as far as I'm aware, not covered by the spec, it's left as a Quality of Implementation issue.

**Comment by peterbrightwell** [comment]
Is any clarification needed in the spec before we close this and publish v1.1.1?

**Comment by peterbrightwell** [comment]
I am going to say not (#107 is tagged enhancement) and closing.
