### ISSUE TITLE
About "rtp_enabled"

### ISSUE THREAD

**Issue by ghost** [AMWA-TV/nmos-device-connection-management#143]
Hi!

According to the [RTP Behavior](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/docs/4.1.%20Behaviour%20-%20RTP%20Transport%20Type.md):

`A Receiver sets the rtp_enabled parameter to true for each leg it has configured from the SDP file, unless overridden by the requested transport_params as noted below.`

Is this a requirement (MUST)?

Is there any special behavior of `rtp_enabled` for Senders that we should take care of?

Thanks in advance.

**Comment by prince-chrismc** [comment]
> Is this a requirement (MUST)?

A few sections up, this attribute is a MUST [here](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/docs/4.1.%20Behaviour%20-%20RTP%20Transport%20Type.md#parameter-sets)

> Receiver Connection Management endpoints MUST support a core parameter set. 
>
>Receiver Parameter Sets
>Core Parameters
> - source_ip
> - interface_ip
> - destination_port
> - rtp_enabled

The text you point out is the _definition_ of the `rtp_enabled` value, or how it's filled, I believe it is included in that MUST.

You can always confirm with NMOS Testing Suite when in doubt. [IS-05-02 test_18](https://github.com/AMWA-TV/nmos-testing/blob/acb26dcad0543eae6be0498f8687dc024a993b66/nmostesting/suites/IS0502Test.py#L1084) checks these requirements

***

> Is there any special behavior of rtp_enabled for Senders that we should take care of?

Given the examples in https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/docs/4.1.%20Behaviour%20-%20RTP%20Transport%20Type.md#interpretation-of-sdp-files

This statement also appears to holds true for Senders 

> sets the rtp_enabled parameter to true for each leg it has configured from the SDP file

**Comment by garethsb** [comment]
The attribute MUST be included, but I think the question is whether the behaviour in response to a single-legged SDP file being `PATCH`ed to a Receiver is REQUIRED or not. I think the answer is yes, and I think the reason it still just says "sets" rather than "MUST set" is because we couldn't adjust conformance language keywords in an editorial revision.

On the other point, the Sender behaviour is _not_ covered by those examples, they show how a Receiver is required to adjust its `transport_params` on being `PATCH`ed only.

However, a two-legged Sender may support `rtp_enabled` being set to `false`, and I need to double check how this is supposed to be indicated in the `/transportfile` endpoint SDP file.

**Comment by ghost** [comment]
Cool, thanks!

**Comment by garethsb** [comment]
Regarding Sender `rtp_enabled`, I've researched this. NMOS does not specify how a disabled leg should be indicated in the Sender's SDP file. There is an [RFC 4566 `a=inactive`](https://datatracker.ietf.org/doc/html/rfc4566#page-27) media-level attribute that could have been used, as previously mentioned in https://github.com/AMWA-TV/nmos-device-connection-management/issues/109#issuecomment-598721418, but that suggestion is not part of the IS-05 spec nor I suspect widely implemented by NMOS devices.

My recommendation is that if the Controller/User wants to configure the Receiver to match the Sender, then to include Sender's `rtp_enabled` alongside a Sender's SDP file when `PATCH`ing a Receiver.

**Comment by garethsb** [comment]
> the question is whether the behaviour in response to a single-legged SDP file being `PATCH`ed to a Receiver is REQUIRED or not.

Quoting from the section on SMPTE 2022-7:
> Where a Receiver supports SMPTE 2022-7 but receives a request with a non-SMPTE 2022-7 transport file, the Receiver SHOULD set `rtp_enabled` in the second set of parameters to `false` and transport parameters in the SDP file SHOULD be mapped onto that first set of parameters in the array with `rtp_enabled` set to `true` (bearing in mind that the `transport_params` values in the same request take priority).

Obviously, it's ridiculously frustrating that those SHOULDs aren't MUSTs, but the desired behaviour is at least specified.
