### ISSUE TITLE
Typos in ConnectionAPI.raml

### ISSUE THREAD

**Issue by jack-fellows** [AMWA-TV/nmos-device-connection-management#15]
In [/APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/APIs/ConnectionAPI.raml), the 400 response for post to /senders and /receivers is missing a negation.

* [Line 65](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/APIs/ConnectionAPI.raml#L65) should begin: "The body of the request did ***not*** validate against the schema ..."
* [Line 101](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/APIs/ConnectionAPI.raml#L101) should begin: "The body of the request did ***not*** validate against the schema ..."

**Comment by simonrankine** [comment]
Well spotted, thank you. Fixed in 73b8e407746f85415f4119fc576796a2af6b3b3f
