### ISSUE TITLE
Space in SDP source filter examples?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#153]
Phil Nguyen noticed there is an error in the examples for IS-05 where there is no space between the colon and “incl”  in a=source-filter:incl:

https://specs.amwa.tv/is-05/releases/v1.1.1/docs/4.1._Behaviour_-_RTP_Transport_Type.html

```
a=source-filter:incl IN IP4 233.252.0.1 198.51.100.1 198.51.100.2
```
 
From:

https://datatracker.ietf.org/doc/html/rfc4570

```
a=source-filter: <filter-mode> <filter-spec>
```
 
Without the space, it fails SDPoker validation and likely the IS-05 NMOS test suite test which uses SDPoker.

Should the examples in the AMWA IS-05 specs be fixed to include that space?

**Comment by garethsb** [comment]
Unfortunately I know of many implementations that get it wrong despite that we check it in the test suites, so as much as it pains me I recommend handling both forms. Other specs do not help, several of the bad examples in IS-05 are taken directly from https://datatracker.ietf.org/doc/html/rfc7104#section-4 for which there's not even an IETF erratum.

Clear reference that the space is required is the ABNF in https://datatracker.ietf.org/doc/html/rfc4570#appendix-A.

**Comment by andrewbonney** [comment]
Checking back over e-mail, this was an issue in the original version of ST.2110-10's examples. I believe this was fixed in the revision. I agree that the examples should be fixed to correspond to the RFC.
