### ISSUE TITLE
Example port constraints

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#156]
The examples in IS-05 that use `"minimum": 49151` are strange. `"minimum": 49152` (first Dynamic Port) or `1024` (first User Port) would make much more sense as an example. See [IANA Port Number Registry](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml).

Suggestion:

```json
  "minimum": 49152,
  "maximum": 65535
```

and/or:

```json
  "minimum": 1024,
  "maximum": 49151
```

**Comment by peterbrightwell** [comment]
Or as 1024 and 49151 are IANA reserved the second example could be:

```json
  "minimum": 1025,
  "maximum": 49150
```

**Comment by garethsb** [comment]
Another reference - https://www.rfc-editor.org/rfc/rfc3551.html#section-8
