### ISSUE TITLE
Why there is no api selector for the IS-05 control endpoint similar to IS-08?

### ISSUE THREAD

**Issue by VenkateswaranJ** [AMWA-TV/nmos-device-connection-management#164]
Just wonder why we don't have an API selector path parameter in the IS-05 control endpoint similar to the IS-08 (https://specs.amwa.tv/is-08/releases/v1.0.1/docs/2.0._APIs.html#api-paths) 

Let's say, I have 100 devices in a node and expose senders and receivers of all those devices to a single connection endpoint doesn't looks flexible isn't it? Of course, I can choose different endpoints by changing the ip address and port, but in most cases, implementers like to expose the IS-05 connection endpoints as well as IS-08 channelmapping endpoints of devices to the same ip:port where node API is running.

When someone patches the IS-05 sender via control software, the nmos implementation needs to know two things senderId and deviceId (where this sender belongs) otherwise on the implementation side, one has to loop through all the devices and then all the senders in those devices to find it (just to set transport parameter for it). In some implementations, it's not the case since the senderId is unique per node and they can trace it quicker. But intuitively the senders, receiver, IS-08 inputs, and outputs are grouped per device so it would be nice to get the device id of them via path param in the API endpoint, isn't it?

Please correct me if I'm wrong!

**Comment by garethsb** [comment]
> on the implementation side, one has to loop through all the devices and then all the senders in those devices to find it

For a given Sender, use `device_id` to discover associated Device `id`, then check `controls` for Connection API, Channel Mapping API, etc. I can't imagine an implementation which doesn't have optimized look up of resources by their `id`.

> Let's say, I have 100 devices in a node and expose senders and receivers of all those devices to a single connection endpoint doesn't looks flexible isn't it?

Let me ask the question the other way... What is the advantage to the Node implementation to having multiple control APIs on the same host rather than one of each API?

**Comment by VenkateswaranJ** [comment]
> For a given Sender, use device_id to discover the associated Device id, then check controls for Connection API, Channel Mapping API, etc. I can't imagine an implementation which doesn't have optimized look up of resources by their id.

How do I know the device Id of the sender from this patch request? -> https://specs.amwa.tv/is-05/releases/v1.1.2/APIs/ConnectionAPI.html#single_senders__senderid__staged_patch

But for IS-08, I can easily say that this Activation post is for the device X, by mapping the device id to the API selector ->
https://specs.amwa.tv/is-08/releases/v1.0.1/APIs/ChannelMappingAPI.html#map_activations_post

I can understand your point that the underlying device has to keep the record of the IS-04 sender (which has the device id as its field).

But when you create a nmos lib (which can be integrated into underlying devices, for example - Sony nmos cpp), it is better to expose API to the underlying devices as

something like this 
patchSender(deviceId, senderId, transportParam)

instead of this
patchSender(senderId, transportParam)

maybe I'm wrong, but the point is when I get the patch request for the sender/receiver, the nmos lib (it just acts as a rest server so that the underlying device doesn't need to worry about rest details such as schema validation etc.,) has to forward this request to the underlying device implementation, but in the underlying device the senders/receivers are grouped per device but the patch request doesn't have device id so it's quite hard for the underlying device to find the sender.

**Comment by garethsb** [comment]
An NMOS library like nmos-cpp will almost certainly need to manage both the IS-05 resources associated with the Sender and the IS-04 resources in order to manage e.g. updating IS-04 resource `subscription` and `version` on activations. Therefore this library could easily determine `device_id` to pass to underlying device implementation.

If this is an nmos-cpp question, better to move the discussion to github.com/sony/nmos-cpp. 😃

**Comment by VenkateswaranJ** [comment]
One last question before closing the issue, is that mean the library has to cache the IS-04 resources (and maintain the record for every change)?

**Comment by garethsb** [comment]
If you're talking about a library to help Node implementers, surely it has to maintain the IS-04 resources to implement the Node API?

**Comment by peterbrightwell** [comment]
Architecture Review Group review: closing as looks to be resolved
