### ISSUE TITLE
Clarification on handling IS-05 sender patch request

### ISSUE THREAD

**Issue by VenkateswaranJ** [AMWA-TV/nmos-device-connection-management#165]
Assuming the NMOS device has just booted and it has an **RTP audio sender** that is not yet configured with transport parameters, I have discovered the sender and its connection management API (IS-05) through IS-04. I have sent the following patch request via an NMOS control software:
```
{
  "receiver_id": null,
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null
  },
  "transport_params": [{
    "source_port": 5000
  }]
}
```
**How the sender should react to this request?** The RTP transport parameter provided in the request contains only the `source_port`. However, it is indeed not possible to configure the sender in a meaningful way without at least specifying the `destination_ip`. 

In another way, why there is no required field in the RTP transport schema https://specs.amwa.tv/is-05/releases/v1.1.2/APIs/schemas/with-refs/sender_transport_params_rtp.html

**Comment by garethsb** [comment]
> why there is no required field in the RTP transport schema

Because it must be possible with `PATCH` request to only update some parameters into _/staged_ and leave the other parameters unchanged.

> it is indeed not possible to configure the sender in a meaningful way without at least specifying the `destination_ip`.

That's true. However, it is the responsibility of the sender to populate the _/staged_ endpoint with initial values for all properties that it uses. The initial value for `destination_ip` can be `"auto"`. As described in the schema you linked, "If auto is set [when an activation occurs] the sender should select a multicast address to send to". The mechanisms for that which are mentioned (MADCAP, ZMAAP) may well not be appropriate for your product, but there are other possibilities, such as assigning a pseudo-random SSM address, or getting the initial value via some proprietary configuration mechanism.

A typical control system is actually almost certain to configure `destination_ip` so that it has a known value appropriate for the network, but the above is how a sender should behave when that doesn't apply.

**Comment by VenkateswaranJ** [comment]
> That's true. However, it is the responsibility of the sender to populate the /staged endpoint with initial values for all properties that it uses. The initial value for destination_ip can be "auto".

If I understand correctly, In the above example the **/staged** endpoint should respond as below
```
{
  "receiver_id": null,
  "master_enable": true,
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time": null
  },
  "transport_params": [{
   "source_ip": "auto"
    "source_port": "auto",
   "destination_ip": "auto",
   "destination_port": "auto"
  }]
}
```
and the **/active** endpoint should respond as below

```
{
  "receiver_id": null,
  "master_enable": true,
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time": null
  },
  "transport_params": []
}
```

Now if I get a patch request without `destination_ip` I consider it as `auto` because I'm already exposing it via **/staged** endpoint, so the controller should somehow know this sender auto-configured for multicast. Am I right?

**Comment by garethsb** [comment]
Do you mean those responses to `GET` requests at boot up before the `PATCH` request?

If so, the _/staged_ response is nearly OK... it must also have at least `rtp_enabled`.
The _/active_ response is not OK, it needs to include all the transport parameters as well.
Although the schema has no required parameters for the reason I mentioned, the _/staged_, _/active_ and _/constraints_ endpoint responses must always include all parameters that the sender supports.

**Comment by VenkateswaranJ** [comment]
> The /active response is not OK, it needs to include all the transport parameters as well.

How? The sender is not configured with any meaningful transport parameter to expose in the **/active** endpoint and it expects nmos to do the initial configuration.
Is it mandatory for IS-05 Sender/Receiver should have a default configuration at the start-up?

**Comment by garethsb** [comment]
> Is it mandatory for IS-05 Sender/Receiver should have a default configuration at the start-up?

Yes.

My recommendation:

```json
{
  "receiver_id": null,
  "master_enable": false, // indicate not actually transmitting at start up
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time":  null
  },
  "transport_params": [{
    "source_ip": "192.0.2.0", // put actual interface IP address in here
    "destination_ip": "233.252.0.0", // use this (MCAST-TEST-NET) address or generate a repeatable pseudo-random SSM (232/8) address
    "source_port": 5004,
    "destination_port": 5004,
    "rtp_enabled": true
  }]
}
```

**Comment by VenkateswaranJ** [comment]
make sense.

> Yes.

Could you please point me to where it's mentioned as **mandatory default configuration** in spec? I don't see that statement.

**Comment by garethsb** [comment]
In the testing tool, IS-05-01 test_09 and test_11 check that the transport parameters follow these rules about _/constraints_, _/staged_ and _/active_.

I can't find a single completely clear statement in the spec...

> Sender and Receiver Connection Management endpoints MUST support a core parameter set.
> ...
> Endpoints MUST support all parameters in a parameter set, or none at all.

[Reference](https://github.com/AMWA-TV/is-05/blob/v1.1.x/docs/Behaviour%20-%20RTP%20Transport%20Type.md#parameter-sets)

...Although it's not clear what "support" means...

> The response will always contain the full set of parameters in the response schema, and all supported transport parameters.

[Reference](https://github.com/AMWA-TV/is-05/blob/d18748f078b34a827b9c5ddcd3d2211f0a3c633a/APIs/ConnectionAPI.raml#LL241C19-L242C51)

...Although that is only stated for the `PATCH` response not the `GET` response...

I'll add this to the ARG backlog to see if I've missed something and/or an editorial clarification is necessary.

**Comment by VenkateswaranJ** [comment]
Based on your [recommended start-up config ](https://github.com/AMWA-TV/is-05/issues/165#issuecomment-1600732967)

We are setting some default multicast IP from test net or some pseudo ip, now **what happens if the controller sends the below patch request?**

```
{
  "master_enable": true
}
```
should the sender just start streaming to the multicast ip address from the **MCAST-TEST-NET**?

**Comment by garethsb** [comment]
Unless there is also an `activation`, your patch only affects the _/staged_ endpoint of course. With an immediate activation included, all the properties from the _/staged_ endpoint are moved to _/active_ replacing whatever was there before. Any `"auto"` values are resolved... if the _/staged_ `destination_ip` was `"auto"` then the sender has to decide what that means... so that then does bring us back to the question you are asking: needing a sender-decided address that you can start streaming to.

**Comment by VenkateswaranJ** [comment]
What I understand from [this reference](https://github.com/AMWA-TV/is-05/blob/v1.1.x/docs/Behaviour%20-%20RTP%20Transport%20Type.md#parameter-sets) is that the IS-05 sender/receiver should support all the core parameters, which means it must be capable of accepting patch requests from control software with all these core parameters. However, it does not explicitly state that the **/active** endpoint should always reflect some value for these core parameters, does it?

The /active endpoint should reflect the running configuration of the sender, but why do we need to force the sender to choose default values for all the core parameters, **even when the master_enable is set to false?**

Perhaps it makes little sense when the `master_enable` is set to `true` because, in that case, we can argue that the sender is running and should have values for all the core parameters.

I have noticed that the NMOS test suite does not run certain tests when the master_enable is set to false.

**How does the controller behave while patching?** 
Sometimes, I feel that NMOS needs a very strict specification on how the controller should behave when interacting with each standard (IS-04, 05, 07, 08, etc.). Currently, we are only providing some suggestions here and there.

Since I'm exposing some random values in the `/active` endpoint (just to satisfy the schema), the controller might assume those are valid configurations in the underlying sender. Consequently, it may fetch the config from the /active endpoint and make changes (for example, changing the source port) and /stage again.

I'm not sure if you can understand the problem here. In short, forcing the sender/receiver to choose random default values for all the core parameters, even when it's not enabled, doesn't seem correct to me.

I can understand the `/constraints` and `/staged` endpoints should reflect some values otherwise it's not possible for the controller to know whether the RTP sender is single leg or 2022-7.

Also, IMHO isn't it nice to have a type representation for single and 2022-7 RTP transport parameters in the schema itself instead of representing as a list of transport parameters and mentioning in the comment like `for 2022-7 this list should contain two value and for the normal sender, it should contain 1 value. The list should not be empty etc.,`
https://specs.amwa.tv/is-05/releases/v1.1.2/APIs/schemas/with-refs/sender_transport_params_rtp.html
What I mean is instead of `List<sender_transport_params>` we can have types like `rtp_sender_transport_param` (which has only one leg) & `rtp_sender_transport_param_dash_7` (which has two legs) or something like that.

**Comment by garethsb** [comment]
> Sometimes, I feel that NMOS needs a very strict specification on how the controller should behave when interacting with each standard (IS-04, 05, 07, 08, etc.). Currently, we are only providing some suggestions here and there.

There was a specific AMWA activity that started to address this, adding Controller sections to IS-04, IS-05, BCP-003-xx, etc. And as another result, new specs are evaluated for how they address Controller requirements. But if you think about it, it is harder to mandate client behaviour than server behaviour. If you would like to scope and contribute to a new activity to build on that work, please bring it up in the AMWA Incubator.

> isn't it nice to have a type representation for single and 2022-7 RTP transport parameters in the schema itself

The spec says no, because other transports may support more than two path redundancy. And in the case of ST 2022-7 exactly the same transport parameters are required for each leg.

> However, it does not explicitly state that the **/active** endpoint should always reflect some value for these core parameters, does it?

Based on implementers' interpretation of the spec over the last 5+ years, and the behaviour of the AMWA test suite used in JT-NM Tested,  etc., the behaviour I described is intended by the spec. It can be clarified editorially.

Your concern seems mostly to be with `destination_ip` for which MADCAP, ZMAAP or a default value in the SSM range, or even `0.0.0.0`, works. Basically every other property has a sensible or harmless default mentioned in the spec.

**Comment by VenkateswaranJ** [comment]
> Other transports may support more than two path redundancy.

But for RTP it's Either one leg or two legs (in 2022-7 case). `Other transports` you mean mqtt, wesocket etc.,?

**Comment by garethsb** [comment]
Theoretically I believe it's possible to use more than 2 redundant paths for RTP. The restriction on the number of legs permitted by the spec was removed more than 4 years ago for future flexibility. I do not see why we should reopen that now.

In the particular case of current ST 2022-7 enabled devices, it is already required that the number of legs is consistent between IS-05 _/staged_, _/active_, _/constraints_ and IS-04 `interface_bindings`.

**Comment by VenkateswaranJ** [comment]
https://github.com/AMWA-TV/is-05/issues/165#issuecomment-1602301623

> The /active endpoint should reflect the running configuration of the sender, but why do we need to force the sender to choose default values for all the core parameters, even when the master_enable is set to false?

Do you have any comments on this point?

**Comment by garethsb** [comment]
As I said, "Based on implementers' interpretation of the spec over the last 5+ years, and the behaviour of the AMWA test suite used in JT-NM Tested, etc., the behaviour I described is intended by the spec." I do not see how removing this requirement at this time would significantly improve ease of implementation or interoperability.

**Comment by peterbrightwell** [comment]
@garethsb: we looked at this on ARG triaging call today (2023-06-23). It doesn't look like there is an action coming out of this, should we close?

**Comment by VenkateswaranJ** [comment]
@garethsb Appreciate your time and response.

**Comment by garethsb** [comment]
@peterbrightwell based on the useful discussion here, I think it would be beneficial to add clarification editorially that _/active_ response needs to contain all supported transport parameters at all times. And possibly more info on choosing a default/initial `destination_ip`.

**Comment by peterbrightwell** [comment]
Architecture Review Group review: close and create backlog item to clarify as per @garethsb's comment above.

**Comment by MichalChomo** [comment]
Hello @garethsb , I'd like to clarify some things regarding the default values (when Receiver/Sender is created but not PATCHed) of `master_enable` and `rtp_enabled`. You've written in this discussion that:
> ... Basically every other property has a sensible or harmless default mentioned in the spec.

I have found only [this section](https://specs.amwa.tv/is-05/releases/v1.1.2/docs/APIs_-_Server_Side_Implementation.html#uninitialised-senders-and-receivers) that says

> Senders and Receivers SHOULD present sensible default values on transport parameter endpoints. Suggested defaults are given in the relevant schemas.

Are these *the relevant schemas*?
[receiver-active-get-200-uninit.json](https://specs.amwa.tv/is-05/releases/v1.1.2/examples/receiver-active-get-200-uninit.html)
[sender-active-get-uninit.json](https://specs.amwa.tv/is-05/releases/v1.1.2/examples/sender-active-get-uninit.html)

If so, why is there a difference between Receiver and Sender defaults? Receiver has `"master_enable": true` and `"rtp_enabled": true` while the Sender has `"master_enable": true` and `"rtp_enabled": false`.

Both of those also differ from [your recommendation](https://github.com/AMWA-TV/is-05/issues/165#issuecomment-1600732967) which has `"master_enable": false`.

**Comment by garethsb** [comment]
@MichalChomo 

> Are these _the relevant schemas_?
> [receiver-active-get-200-uninit.json](https://specs.amwa.tv/is-05/releases/v1.1.2/examples/receiver-active-get-200-uninit.html)
> [sender-active-get-uninit.json](https://specs.amwa.tv/is-05/releases/v1.1.2/examples/sender-active-get-uninit.html)

Those are examples, not schemas.

Regarding `master_enable` at start up specifically, this is easy, it's the first rule of NMOS - what you report in your NMOS APIs should reflect the underlying state of the data plane. If you start up transmitting, or start up actively receiving, then `master_enable` should be `true`. If your next question is whether you should start up active or not, check the JT-NM TR-1001-1 spec for guidance based on whether the network environment is the same as when you powered down.

**Comment by MichalChomo** [comment]
> Those are examples, not schemas.

I see, you're right. In that case, I'm not sure if this sentence from [the docs](https://specs.amwa.tv/is-05/releases/v1.1.2/docs/APIs_-_Server_Side_Implementation.html#uninitialised-senders-and-receivers) is true:

> Suggested defaults are given in the relevant schemas.

I cannot see a suggested default value for `rtp_enabled` anywhere in
[receiver_transport_params_rtp.json](https://specs.amwa.tv/is-05/releases/v1.1.2/APIs/schemas/receiver_transport_params_rtp.json)
[sender_transport_params_rtp.json](https://specs.amwa.tv/is-05/releases/v1.1.2/APIs/schemas/sender_transport_params_rtp.json)

Regarding the `master_enable`, thank you, I will check the spec.

**Comment by garethsb** [comment]
Same applies to `rtp_enabled` in _/active_ - it should reflect how the underlying transmit/receive is currently configured. There are reasonable defaults for ports and recommendations for initial multicast addresses in the absence of any underlying device state, but the latter should always be preferred. If there is no underlying state to use, to me it seems natural that initial `rtp_enabled` is true on all legs and `master_enable` is false.
