### ISSUE TITLE
Clarification on GET /staged behaviour

### ISSUE THREAD

**Issue by Mantls** [AMWA-TV/nmos-device-connection-management#167]
Hey,

How is a Receiver/Sender supposed to respond to GET to it's /staged endpoint in the case of no staged parameters being set yet (such as after having performed some change or fresh boot)?

In Particular how does _transport_prarams_ have to look like? (Empty Objects for each leg? "Sensible" default parameters? nothing?)

**Comment by garethsb** [comment]
All transport parameters that are implemented (following the rules for the different subsets for different features, RTCP, FEC, and so on) MUST be present in /staged, /active and /constraints at all times.

In the case of /staged, the sensible default for many transport parameters that allow it is `"auto"`.

**Comment by Mantls** [comment]
Ok, thanks for clearing that up.
