### ISSUE TITLE
Response on /staged endpoint when sheduled activation failed

### ISSUE THREAD

**Issue by VenkateswaranJ** [AMWA-TV/nmos-device-connection-management#172]
I scheduled a relative activation that failed while applying to the underlying device (due to some internal error).
Now, the /active endpoint should show the current running values, what about the GET request on /staged endpoint? should we show the previously scheduled values (but it's failed while applying to the underlying device) or the state before this failed patch?

**Comment by garethsb** [comment]
I don't think the transport params etc. in the _/staged_ endpoint should be changed when the related activation completes (successfully or failing) - they were successfully staged, just not activated. However the `activation` object attributes should, per the descriptions in the schema, return to `null` to unlock the _/staged_ endpoint.

**Comment by VenkateswaranJ** [comment]
Is this situation also applicable to "immediate activation"? I have encountered a scenario where the underlying device fails when a specific value is used in the transport parameter. Naturally, this value should be listed in the `/constraints` endpoint to prevent a patch attempt with that value in the first place, but it's not there.

Let's consider a case where the underlying device will fail to patch if the "source_ip" in the transport parameter is set to a multicast value. For instance, if I attempt an "immediate patch" with a "source_ip" of 224.0.0.118, the patch request will fail on the underlying device, but it's successfully staged. Subsequently, a GET request to the `/staged` endpoint will display 224.0.0.118 as the source_ip. Is this a valid scenario?

I am concerned about this situation due to how client software attempts to patch the IS-05 sender/receiver. To the best of my knowledge, the software should retrieve values from the `/active` and `/constraints` endpoints when constructing a patch request and should not consider values from the `/staged` endpoint. Is my understanding correct?

**Comment by VenkateswaranJ** [comment]
@garethsb any suggestion for my last comment? or else I'll close this one.

**Comment by garethsb** [comment]
In the IS-05 model, staging and activating are two separate steps. This is obvious in the case of scheduled activations, less so in the case of immediate activations.

Some errors can be recognised and reported at the point of staging, such as if a transport parameter value is out of range. Some of those, such as your example, _could_ be expressed through `/constraints` but the device is not obliged to do so. It should still refuse to stage the requested values and report this in the response to the `PATCH` request. Other errors could be detected at staging but not expressed by constraints, such as if the device requires RTP destination port and RTCP destination port to be in some relationship to each other (e.g. just not the same!). The device could still refuse to stage the values. This applies to both scheduled and immediate activations.

Other errors are never detectable until activation, after the values have been staged... e.g. some device/network resource becomes unavailable between staging and activation. With scheduled activations, errors during staging can be reported in the response to the `PATCH` request, but activation errors can't. In the case of immediate activations, both kinds can be.

So, in your example, I think the scenario you outline _is_ valid, but if the device would always reject multicast addresses it would be better to reject them during the staging phase not the activation phase.

**Comment by VenkateswaranJ** [comment]
Thanks for your response @garethsb
