### ISSUE TITLE
Activation response after unlocking

### ISSUE THREAD

**Issue by btrost-harmonicinc** [AMWA-TV/nmos-device-connection-management#30]
The state change on the staged endpoint isn't clear on this matter, but I believe the text "On the staged endpoint this field returns to null once the activation is completed." should be extended with "...or the resource is unlocked by setting the activation mode to null." This text appears twice in the activation response schema.

Similarly (if even more nit-picky), I believe the activation schema for requests should require that the requested_time be null if the mode is null.

**Comment by simonrankine** [comment]
Thanks for pointing this out - I agree this would be more clear. I'll get that sorted.
