### ISSUE TITLE
Typo in examples/v1.0-receiver-stage-scheduled-absolute.json?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#32]
Presumably this is a typo in the example for absolute-scheduled-activation:

https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/examples/v1.0-receiver-stage-scheduled-absolute.json#L5

```
<        "mode": "activate_scheduled_relative",
---
>        "mode": "activate_scheduled_absolute",
```

**Comment by simonrankine** [comment]
Fix added to upcoming patch for 1.0.x
