### ISSUE TITLE
Typo in examples/v1.0-receiver-stage-scheduled-transportfile.json

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#33]
I haven't looked at the rest of the embedded SDP file, but the lack of a "\r\n" between the initial "v=0" and "o=" line jumped out at me...

https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/examples/v1.0-receiver-stage-scheduled-transportfile.json#L10

**Comment by simonrankine** [comment]
Fix in typo fix branch, awaiting merge into v1.0.x
