### ISSUE TITLE
Extensibility of "transport_params" and /constraints to other transport types

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#34]
The schema for senders’ and receivers’ parameters (for /staged, /active, etc.) breaks out the sub-schemas for their “transport_params”, so in each case we have a separate schema for RTP vs. (the placeholder) for DASH. Four schemas in total.

For both senders and receivers, the schema for RTP parameters requires that the value is an array, to support multi-leg ST 2022-7.

First question – I'm now wondering whether we envisage that other transport types might not have a top-level array, and just be a single object, rather than always an array of one-two(/more)?

Next, look at senders’ and receivers’ /constraints endpoints. Here, if I understand correctly, we’ve currently got a single schema and not separate ones for senders and receivers on the one hand, or separate ones for RTP and other transport types (e.g. even a placeholder for DASH) on the other.

A single schema would make complete sense if it could work with any transport type, e.g. didn’t mention actual property names. However, at the moment - in order to work for both the senders’ and receivers’ /constraints endpoints - we ended up mentioning the union of the RTP parameters for both.

Second question – I'm wondering how we will extend this to support other transport types?

(And the relevance of the first question here is that the /constraints endpoint schema is currently a top-level array, matching the RTP "transport_params", but will that always be the case for other transport types?)

Any thoughts?

**Comment by garethsb** [comment]
I am wondering whether we need something new to actually allow extensibility to support transport types other than RTP.

For example, perhaps the senders and receivers, either in /constraints, or /staged and /active, or both, or somewhere new,  ought to have a "transport" property like Sender and Receiver resources in IS-04.

**Comment by garethsb** [comment]
Cf. PR #51.

**Comment by andrewbonney** [comment]
@garethsb-sony can this one be closed based upon the PR? I believe https://github.com/AMWA-TV/nmos-device-connection-management/issues/57 covers the remaining open issue in this area.

**Comment by garethsb** [comment]
OK.

I can't remember whether making the various array values less constrained is covered anywhere. But that'll come up again if it turns out to be a good idea.
