### ISSUE TITLE
Use of the term "Device"

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#35]
The [Overview](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/docs/1.0.%20Overview.md#introduction) says:

> The terms 'Node', 'Device', 'Sender' and 'Receiver' will be used extensively throughout this document. Please refer to the core [NMOS Technical Overview](https://github.com/AMWA-TV/nmos/blob/master/NMOS%20Technical%20Overview.md) for definitions of these.

It goes on to use the word "Resource" to mean either a Sender or Receiver, or just uses the phrase "Sender or Receiver" repeatedly.

However, in some of the rest of the documentation (e.g. [here](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/docs/2.1.%20APIs%20-%20Client%20Side%20Implementation.md#conforming-to-schemas) and [here](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/docs/2.2.%20APIs%20-%20Server%20Side%20Implementation.md#sender-source_ip-and-receiver-interface_ip)), the word "Device" or the phrase "running Device" is used to mean "Sender or Receiver". That is confusing.

I think it would be better to stick to the clunky "Sender or Receiver", or to use a new term. That might be "Resource" but that's a bit general, so perhaps something like "Connector".

**Comment by btrost-harmonicinc** [comment]
FWIW, I've been using "Endpoint" to describe "Sender or Receiver". "Connector" seems to describe the thing(s) between, not the things an the end, of a Flow.

**Comment by garethsb** [comment]
> FWIW, I've been using "Endpoint" to describe "Sender or Receiver". "Connector" seems to describe the thing(s) between, not the things an the end, of a Flow.

I like Endpoint a lot! A downside is that it's used (with a lowercase e) as the generic term for the URLs to access resources in REST APIs.

**Comment by peterbrightwell** [comment]
We do need to be consistent with the JT-NM terminology, some of which is also reflected in the NMOS Glossary. That already defines "Endpoint" (capital E) as:

Endpoint: the network entry point to a running instance of an Interface.

So can't really use it for this purpose.  I agree that that documentation could be tightened up a bit.

BTW, we will be moving the glossary to the new NMOS wiki at https://github.com/AMWA-TV/nmos/wiki, and will be updating it.

**Comment by garethsb** [comment]
> Endpoint: the network entry point to a running instance of an Interface.

Oh, yes... :-/

> "Connector" seems to describe the thing(s) between, not the things an the end, of a Flow.

Hmm. The JT-NM describes a connection between a Sender and a Receiver as what transports a Flow.

I think of connectors as the things at either end of a cable, or connection.

**Comment by simonrankine** [comment]
This is an issue I ran into a lot when writing both IS-05, and our implementation of it - often you don't care whether you are talking about a sender/receiver, as they are actually just two ends of the same cable in some ways :-/

I actively tried to avoid using "Device" where I didn't mean a JT-NM "Device", but clearly my fingers got away from me in a few places.

Given that we appear to have term in common usage at present to describe something that may either be a sender or receiver, would updating the IS-05 spec to read sender/receiver where applicable be acceptable?

**Comment by simonrankine** [comment]
Going to close this now, as it's not so much an IS-05 issue as a JT-NM terminology issue. I've tried to clear up any areas this might have caused confusion in the spec as it stands in c6f06f1.

**Comment by garethsb** [comment]
@simonrankine the changes to the RAML and schemas look thorough, thanks!

After re-reading the bits of the documentation I previously called out, I can see how the use of Device makes sense in almost all the places. Only in the [Client Side Implementation](https://github.com/AMWA-TV/nmos-device-connection-management/blob/master/docs/2.1.%20APIs%20-%20Client%20Side%20Implementation.md#conforming-to-schemas) page, I do wonder whether a couple of the uses of capitalized "Device" would be better as "Sender or Receiver", e.g. "'/constraints' resource of a running Device". (I've also just noticed an odd typo in the first sentence of the Failure Modes section. Currently reads "If a client Receivers a HTTP 500 response code from the API a failure has occurred.")
