### ISSUE TITLE
More typos

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#36]
(Hit return and submitted this too soon. I may add more later...)

**RAML**

Several uses of "sender/receiver" are a little confusing ("hmm, are these sender wotsits really being validated against receiver thingamijigs?"). Other instances of "sender/receiver" might be OK, but using "resource" or another term (see #35) might be better. Other instances of sender or receiver are just obvious copy & paste typos.

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L66) - sender/receiver --> sender (or resource?)

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L86) - sender --> receiver

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L102) - sender/receiver --> receiver (or resource?)

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L124) - senders --> sender

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L140) - sender/receiver --> sender (or resource?)

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L144) - sender/receiver --> sender (or resource?)

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L160) - receiver --> sender

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L187) - reqest --> request

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L314) - sender/receiver --> receiver (or resource?)

[APIs/ConnectionAPI.raml](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L318) - sender/receiver --> receiver (or resource?)

**Schemas**

[APIs/schemas/v1.0-sender-response.schema.json](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0-sender-response-schema.json#L24) - receiver --> sender

**Comment by garethsb** [comment]
Another minor sort of typo... both the schemas and example files for bulk control have confusing names, due to the history of design. Some files have "stage" in the name, some don't, though there's no "/stage" in the bulk endpoint names. And some have "patch" in the name, when the request operation is always a POST.

**Comment by simonrankine** [comment]
Think these have all been fixed, although no new innovative name for a sender/receiver entity. If you could take a look at the commit and see if it looks right to you I'd be very grateful.
