### ISSUE TITLE
Behaviour of "master_enable" in /single/receivers/{receiverId}/staged

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#37]
In [APIs/schemas/v1.0-receiver-stage-schema.json](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0-receiver-stage-schema.json#L16-L20) we find:

https://github.com/AMWA-TV/nmos-device-connection-management/blob/bef1bc18c625f5f47a3b07b64b029fdc13cacc38/APIs/schemas/v1.0-receiver-stage-schema.json#L16-L20

What does that default value mean when making a PATCH request? If "master_enable" is omitted by the client, should the receiver be enabled? Or is this a copy-and-paste mistake from the response schema?

The equivalent sender stage schema does not have the same default.

**Comment by simonrankine** [comment]
Closing this, as this is also addressed by the commits in #42
