### ISSUE TITLE
Description of "rtcp_source_port" in APIs/schemas/v1.0_sender_transport_params_rtp.json

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#39]
https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0_sender_transport_params_rtp.json#L193

> "description": "source port for RTCP packets (destination port for RTCP packets (auto = RTP destination_port + 1))"

I'm struggling to understand what this means. Did commit aad8764 hit the wrong line by mistake, @simonrankine ?

**Comment by simonrankine** [comment]
Fix in upcoming typo fix patch to 1.0.x
