### ISSUE TITLE
APIs/schemas/v1.0-constraints-schema.json is missing a property!

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#41]
[APIs/schemas/v1.0-constraints-schema.json](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0-constraints-schema.json) is missing a property!

Or at least I can't think of a good reason why ["multicast_ip" from the Receiver params](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0_receiver_transport_params_rtp.json#L27) is not included?

**Comment by simonrankine** [comment]
Fix in typos branch, awaiting merge into v1.0.x
