### ISSUE TITLE
Must/should/may a receiver's "transport_file" be stale?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#48]
The [Connection API receiver /staged](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L354) spec is clear that "transport_params" should be updated to reflect the contents of a PATCHed "transport_file" (if not overwritten by "transport_params" in the same request).

I have been assuming the reverse is never the case, i.e. the contents of the "transport_file" will be as most recently PATCHed.

However, another possibility would be for the most recently PATCHed "transport_file" to be updated to reflect any "transport_params" in the same and subsequent requests. Is that required? Is it prohibited?

Thoughts? @simonrankine, @simonlo-sony, @billt-hlit

**Comment by simonrankine** [comment]
Hi Gareth,

As far as I know IS-05 doesn't specify the behaviour for this, so I suppose you can do what you will. I guess the question is what is the user story that would drive this behaviour? I suppose the most likely case is that a client wishes to ascertain the current behaviour of a receiver by looking at its transport file (I can think of no other reason for wanting to GET that information). In which case, the transport file should probably reflect the current device behaviour at all time. I imagine however most implementations don't do this at present, so it would probably be a foolish control system to assume that would be the case.

If there is a use case that requires a particular behaviour we can look at this for any potential v1.1 releases, but this would really be a normative change to the spec as it would effectively "break" existing implementations.

**Comment by garethsb** [comment]
> As far as I know IS-05 doesn't specify the behaviour for this, so I suppose you can do what you will.

Thanks, that answers my question.

> I guess the question is what is the user story that would drive this behaviour?

Story: an NMOS Connection API is a façade for a device/receiver that is configured solely via SDP, so it needs to perform this transport_params -> transport_file reverse update anyway.
