### ISSUE TITLE
Multi-client operation requirements and what to do about in-flight immediate activations?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#49]
**Background**

The documentation describes behaviour for [Multi-Client Operation](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/docs/4.0.%20Behaviour.md#multi-client-operation). The spec clearly states implementation requirements on [activation responses](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0-activation-response-schema.json) for PATCH vs. GET /staged.

Assume an underlying implementation where activation may take an appreciable length of time.

**What to do about in-flight immediate activations?**

While an immediate activation is in flight, if it concurrently receives a PATCH request on the same resource, an implementation could (thought-experimentally):
(a) block the new request until the in-flight activation is complete (or the API/app is shutting down)
(b) process the new request as if the in-flight one is complete (queue it up somehow?)
(c) return an error (probably has to be 500, not 423, because the spec doesn't allow for an immediate activation to be cancelled, even if the underlying implementation did)

Similarly, a concurrent GET request could:
(a) block
(b) return (i) prior state, (ii) future state (lie), or (iii) an in-flight state (e.g. with mode set to "activate_immediate", but that's explicitly prohibited by the spec)
(c) error (500)

Is the intention of the spec that a PATCH should (a) block, and a GET should (b)(i) return prior state or (a) also block?

If that's so, while a client must obviously expect that an immediate activation takes as long as it takes, it wasn't obvious to me that either a scheduled activation or even a staging-only request could also have to block for a pending immediate activation.

Thoughts? @simonrankine, @simonlo-sony, @billt-hlit

**Comment by simonrankine** [comment]
Again, I think it's important to be driven by use cases here. So as usual my response is going to be IS-05 should reflect the devices state as closely as possible. So, if the device stops sending/receiving during an activation then maybe the GET should have master_enable set to false in that time. If it doesn't then the parameters returned to a GET should change the instant the device behaviour changes.

PATCH is more tricky, I don't think we specify a behaviour for this. I suspect what would have to happen in practice is that the "new" PATCH would have to block until the previous one finished, as again it's all about what the hardware is doing. Given the hardware can't do two transitions at once, neither can IS-05. But again, this isn't in the spec, so client implementors shouldn't rely on this behaviour being consistent and if we need it to be then it'll have to go in the next minor version increment.

**Comment by garethsb** [comment]
Thanks, Simon.

**Comment by garethsb** [comment]
It's not 100% related to this issue, but am I correct in thinking the spec basically says the result of a bulk activation which applies multiple patches to the same resource, is implementation defined? They're not necessarily commutative after all.

POST /bulk/receivers
```
[
	{ "id": "180b865e-6d2e-5b68-80fd-f764fb9e40f9", "params": { "master_enable": true } },
	{ "id": "180b865e-6d2e-5b68-80fd-f764fb9e40f9", "params": { "master_enable": false } }
]
```

It gets even more 'interesting' obviously if either or both of the patches ask for scheduled or immediate activation.
