### ISSUE TITLE
Values for /transporttype and relationship to IS-04 "transport" values

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#57]
Schema for /transportfile endpoint is at https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1-dev/APIs/schemas/transporttype-response-schema.json. This currently contains enumerated values.

I presume this should be updated to match the pattern based schema in https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3-dev/APIs/schemas/sender.json (added by https://github.com/AMWA-TV/nmos-discovery-registration/commit/d6dfff24c8e66658637ab951bb59b65cc4dfce5c).

That commit also added the following in the IS-04 [Common Keys](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3-dev/docs/2.1.%20APIs%20-%20Common%20Keys.md#transport) documentation:

"Note: From v1.3 onwards, permitted transport types are not versioned and are instead defined via the [NMOS Parameter Registers](https://github.com/AMWA-TV/nmos-parameter-registers)."

The table of values below that sentence, and the [transport parameter register](https://github.com/AMWA-TV/nmos-parameter-registers/tree/master/transports) which is to be used instead of it, contains the entries for both the top-level category "urn:x-nmos:transport:rtp" and the subclassifications with ".ucast" and ".mcast" appended.

So the question arises, whether the IS-05 "/transporttype" may be any value from the parameter register, including subclassifications, or only one of the top-level categories? If so, the concept of ‘subclassifications’ and ‘top-level category’ need better definition. Can I trim to the first ‘.’ after the last ‘:’ for instance?

**Comment by andrewbonney** [comment]
A clarification for 'subclassifications' has been added to https://github.com/AMWA-TV/nmos-discovery-registration/pull/78

I'd suggest that the transport enum in IS-05 v1.1-dev should remain, as the versioning of IS-05 is probably best remaining strongly tied to the addition of new transport types. This is less critical in the case of IS-04, hence the pattern added to v1.3-dev.

**Comment by garethsb** [comment]
@peterbrightwell Did you have an opinion about subclassifications and whether IS-04 and IS-05 values should be identical or not?

**Comment by garethsb** [comment]
The discussion in https://github.com/AMWA-TV/nmos-discovery-registration/pull/78 made clear the potential to communicate more precise information via URN subclassifications and versioning, and resulted in more well-defined rules about how to get the 'base' URN from one with subclassifications or version suffix.

On that basis, despite that we feel IS-05 versions are more closely tied to the range of supported transport types, I propose that it should be acceptable to return a URN with subclassification (and versioning if that were introduced for ``urn:x-nmos:transport:`` URNs) from the ``/transporttype`` endpoint. Clients can easily form the 'base' URN.

If we want the schema for IS-05 v1.1 to limit the range of supported transport types, it could have constraints that still allow subclassifications/versions something like:

```json
{
  "type": "string",
  "format": "uri",
  "oneOf": [
    {
      "pattern": "^urn:x-nmos:transport:rtp(\\..+)?$"
    },
    // ...
    {
      "not": {
        "pattern": "^urn:x-nmos:"
      }
    }
  ]
}

**Comment by jasperpeeters** [comment]
> I propose that it should be acceptable to return a URN with subclassification (and versioning if that were introduced for `urn:x-nmos:transport:` URNs) from the `/transporttype` endpoint. Clients can easily form the 'base' URN.

Stumbled upon this now as well -- and support your proposal.

**Comment by andrewbonney** [comment]
Any further thoughts on this one? It's worth noting if we permit URNs like `urn:x-nmos:transport:rtp.ucast` and `urn:x-nmos:transport:rtp.mcast` we'll need to be careful about specifying behaviour when a Sender or Receiver is re-configured. If a Sender destination IP is changed it may change the URN used in `/transporttype` which (however tightly we specify it) will have the potential to confuse implementations.

**Comment by garethsb** [comment]
That's interesting. Do the IS-05 `/transporttype` and/or the IS-04 Sender `"transport"` reflect the current configuration, or the capability?

**Comment by andrewbonney** [comment]
For IS-04 at least this is noted in https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/2.1.%20APIs%20-%20Common%20Keys.md#transport. The text suggests that on the Sender side it reflects configuration and on the Receiver side capability. This is of course not ideal, and 'capability' should probably be handled in 'caps' rather than in this URN.

**Comment by garethsb** [comment]
So, if I understand correctly, it is already the case that a PATCH /staged on an IS-05 Sender that switched between multicast and unicast addresses for `"destination_ip"` should change the IS-04 Sender `"transport"`?

**Comment by andrewbonney** [comment]
If you were to follow the docs text of IS-04 to the letter then yes I believe that's what should happen. Whether this has been universally adopted or not I'm unsure.

**Comment by garethsb** [comment]
Deciding to update `/transporttype` - or not - seems quite similar.

**Comment by andrewbonney** [comment]
It does, but the question for me is whether we should be matching existing behaviour elsewhere for complete consistency, or doing something simpler based upon practical issues we've observed in implementations. Is there a notable benefit to permitting sub-classifications here which outweighs the potential for clients to trip up over them (and servers to mis-implement)?

If matching existing behaviour is the group preference then the existing dev schemas should be changed. I'm unconvinced personally, but it's a relatively minor detail so there's no point spending loads more time on it.

**Comment by garethsb** [comment]
We have this issue due to a naive implementer wondering whether he could just copy IS-04 Sender `"transport"` into IS-05 Sender `/transporttype`.

We could stick with the v1.0 status quo... What if we added a sentence to ConnectionAPI.raml and/or schemas/transporttype-response-schema.json to explicitly say the value should be the _URN base_ transport type (i.e. with any _subclassification_ or _version_ removed), with a link to the docs added by https://github.com/AMWA-TV/nmos-discovery-registration/pull/78 (although to avoid referring to IS-04, perhaps those words should be in the Parameter Registers instead)?

**Comment by andrewbonney** [comment]
That would be fine by me. I don't know if others wish to comment?

The IS-04 reference issue should hopefully go away once we have NMOS Core defined. There is still some chance of that happening before this version is complete, but yes otherwise the parameter registers may be a better place for the time being.

**Comment by andrewbonney** [comment]
Closing this given the clarification made. If there are any further queries please re-open this or create a new issue.
