### ISSUE TITLE
Should server set sender_id to null when client does a patch of the staged with just an SDP?

### ISSUE THREAD

**Issue by jwpwh** [AMWA-TV/nmos-device-connection-management#59]
When the nmos-explorer (version 1.1.1) is used to Paste an SDP into a receiver, the staged parameters just get a transport file. Should the IS-05 server set the sender_id in the staged parameters to null when this is done? Or should the IS-05 server count on the client to explicitly include a null sender_id?

In https://raw.githubusercontent.com/AMWA-TV/nmos-device-connection-management/v1.0.x/APIs/schemas/v1.0-receiver-stage-schema.json the description for sender_id indicates that the sender_id should be null if the receiver has not been configured to receive anything or if it is receiving from a non-NMOS sender. When just an SDP file is supplied, it isn't clear that the SDP file is associated with any NMOS sender so null might be appropriate. On the other hand, perhaps the client is supposed to know what is going on and explicitly set sender_id to null.

**Comment by andrewbonney** [comment]
Hi. Sorry for the delay in replying. The expectation in these cases is that the client passes in the correct information and that the IS-05 server doesn't make any assumptions. It is possible (for example) that the client may wish to correct a single transport parameter which was incorrect. When doing this the client isn't expected to re-affirm that it's still talking about the same sender_id or receiver_id.

The onus being on the client is alluded to in https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/docs/3.2.%20Interoperability%20-%20Non-NMOS%20Devices.md#interacting-with-non-nmos-devices, but I'd agree that it doesn't appear to be 100% clear for all cases so we may need to add a clarification around this behaviour.

**Comment by jwpwh** [comment]
Thanks for the response. The expectation that the client is responsible for setting all the correct information seems reasonable.

I have no further questions. If you want to close the issue, that is fine. If you want to leave it open until a clarification is added, that would be good too.

Thanks again.

**Comment by andrewbonney** [comment]
No problem. I'll leave it open as a reminder that an action is required for now.
