### ISSUE TITLE
Should IS-04 control entry for the IS-05 API have a trailing slash?

### ISSUE THREAD

**Issue by btrost-harmonicinc** [AMWA-TV/nmos-device-connection-management#65]
This came up at the Houston interop: The example "controls" entry for the IS-04 Device in chapter 3.1 of the documentation has a trailing slash in its "href":
```
"controls": [
  {
    "type": "urn:x-nmos:control:sr-ctrl/v1.0",
    "href": "http://192.168.10.3/x-nmos/connection/v1.0/"
  }
]
```
Similarly, the "API Paths" of section 2.1 states the format for an NMOS API MUST use a path like `http(s)://<ip address or hostname>:<port>/x-nmos/<api type>/<api version>/` (note the trailing slash). However, in discussion regarding issues I submitted about this regarding [the Sony implementation](https://github.com/sony/nmos-cpp/issues/58) and [the IS-04/-05 tests](https://github.com/AMWA-TV/nmos-testing/issues/139), there is some belief that the section titled "URLs: Approach to Trailing Slashes" in chapter 2.0 should apply, and that no trailing slashes should appear in the "controls" entries.

Presuming we can come to agreement on what the correct behavior is, can we correct the examples and/or text to match? In particular, some explicit text along with the example "controls" attribute would be helpful.

**Comment by garethsb** [comment]
Thanks for raising this here, Bill.

I agree that it's a good idea to confirm whether either the trailing slash or its absence is _REQUIRED_ or (only) _RECOMMENDED_ here and make all parts of the specification reflect that.

The specifications have a lot of guidance for server implementations on responding to requests with and without trailing slashes, whether directly or via a redirect. I think what we're missing, unless one or other approach is confirmed as mandatory, is some guidance for _clients_ on how to use the URL, such as Andrew mentioned in https://github.com/AMWA-TV/nmos-testing/issues/139#issuecomment-466339964, "at the very least trim trailing slashes and explicitly re-add one" before e.g. adding "single/senders".
