### ISSUE TITLE
PATCH "transport_params" with empty array?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#68]
Is it valid to send a request like this?

``PATCH /x-nmos/connection/v1.0/single/receivers/{receiverId}/staged``

```json
{
  "transport_params": []
}
```

The specification, [here](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L378-L380), uses *shall* regarding the number of items in the `"trasnport_params"` array. The schema does not validate that (the required number, one or two, would depend on whether ST 2022-7 is in use).

Note that there are two other entirely valid ways of specifying no transport parameters in the PATCH request, (a) omit `"transport_params"` entirely, or (b) make its value `[{}]` or `[{}, {}]` as appropriate.

**Comment by garethsb** [comment]
To go further, if we decide to allow a client to send an empty array, we also have to define the meaning of sending a _one_ element array when the receiver has two legs.

Or for that matter, the meaning of sending a _three_ element array...

**Comment by andrewbonney** [comment]
I'd suggest that the 'preferred' method for sending this request ought to be to omit 'transport_params' entirely if it contains no modifications (as noted in the 'activation-only' example in the spec https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/examples/v1.0-receiver-patch-activation-only.json). If it doesn't exist already then we may need to add an explicit note that any parameter which isn't modified SHOULD? NOT be included in PATCH requests from clients. That could be strengthened to a MUST if desired, but even so I'd hope that server implementations would follow the robustness principle https://tools.ietf.org/html/rfc1122#page-12.

I don't think we should really try to cover all of the bases for an empty change in the spec as there are no doubt many other areas where this sort of thing could occur. We do however need to be clear about the preferred option.

Strengthening the requirement to include an object in each element of the transport_params array when actually making a modification may also be necessary, potentially with an example such as the following where only one 'leg' is modified:

```
{
  "transport_params": [{}, {"rtp_enabled": false}]
}
```

I believe the use of three element and greater arrays is technically limited by https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/schemas/v1.0-constraints-schema.json#L6.

**Comment by garethsb** [comment]
That all makes sense, and the one 'leg' modification is a good example.

However, to turn that around, it seems to me that a client should be required to send:

```json
{
  "transport_params": [{"rtp_enabled": false}, {}]
}
```

to change the property of only the first 'leg'.

On a two-legged sender/receiver, didn't the following ought to generate an error, because it seems more than likely that the client is flawed and thinks it's dealing with a one-legged sender/receiver?

```json
{
  "transport_params": [{"rtp_enabled": false}]
}
```

This leads me to argue that the robustness principle is not the right touch-stone here.

(You're right about the three-element case right now, I'd forgotten that, though it is something that might need revisiting (remembering the "first question" and last comment in #34).)

**Comment by andrewbonney** [comment]
> However, to turn that around, it seems to me that a client should be required to send:
> 
> ```json
> {
>   "transport_params": [{"rtp_enabled": false}, {}]
> }
> ```
> 
> to change the property of only the first 'leg'.

I agree. I should have been explicit about which leg I was talking about modifying in the example.

> On a two-legged sender/receiver, didn't the following ought to generate an error, because it seems more than likely that the client is flawed and thinks it's dealing with a one-legged sender/receiver?
> 
> ```json
> {
>   "transport_params": [{"rtp_enabled": false}]
> }
> ```

Yes, I think this request should cause an error for a two-legged sender/receiver based upon what you noted in https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L378-L380. As I say this text may just need strengthening slightly in regard to this case, ie. if transport_params is specified in the request, the number of array elements MUST match the number of legs. By extension this would make the original subject of the issue (as below) an invalid case.

```
{
  "transport_params": []
}
```

**Comment by garethsb** [comment]
Exactly!
