### ISSUE TITLE
IS-05 v1.1-dev "ext_" patternProperties regex is wrong

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#69]
Unless I misunderstood, all 5 instances of the "ext_" patternProperties introduced into v1.1-dev by https://github.com/AMWA-TV/nmos-device-connection-management/commit/0e159ae57cc0f6e1a4cd47d8b2c35adacbe4e4ea have spaces in where they shouldn't.

`"^ext_[a-z A-Z 0-9 _]+$"` needs condensing to `"^ext_[a-zA-Z0-9_]+$"`

(Aside: we need a note in 'NMOS Core' giving guidance about the character classes used for identifiers/tokens (e.g. how to decide when introducing a new identifier of some kind, whether or not they should allow numbers, hyphens, underscores, upper vs. lowercase, etc.)

**Comment by andrewbonney** [comment]
Yes that looks like an error. Would you mind doing a PR?

**Comment by garethsb** [comment]
Why didn't this get closed automatically? 🤔
