### ISSUE TITLE
Use of "auto" for externally defined transport parameters

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#71]
IS-05 v1.1-dev has added support for [externally defined parameters](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1-dev/docs/4.0.%20Behaviour.md#externally-defined-parameters).

I am interested to know how this interacts with support for [`"auto"`](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1-dev/docs/2.2.%20APIs%20-%20Server%20Side%20Implementation.md#use-of-auto).

Presumably the external definition should include whether or not `"auto"` is supported? And if a client is unaware of the external definition, they can't rely on `"auto"` being valid.

**Comment by andrewbonney** [comment]
Yes, I'd agree that the external definition should signal whether 'auto' is supported or not, as this matches the existing mechanism.

If a client is unaware of how the external parameters work then it should most likely be excluding them from any PATCH requests and assuming that the current values are applicable.

**Comment by garethsb** [comment]
Right. Makes sense. I added https://github.com/AMWA-TV/nmos-event-tally/issues/42.
@andrewbonney, close this?
