### ISSUE TITLE
Potential requirement for additional MQTT parameters

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-device-connection-management#80]
As noted in https://github.com/AMWA-TV/nmos-event-tally/issues/54, it may be necessary to indicate a protocol version (including versions supported via constraints), and any need for a 'secure' parameter should be considered. These could be handled later via 'ext_' parameters but would be better sorted now before finalising this version of the spec.

**Comment by andrewbonney** [comment]
Just noting that the decision in the IS-07 group is to omit these and define defaults or deployment specific agreements (in this case use of TLS or not should match what IS-05 itself is doing and MQTT versions should be agreed by deployment).

If these parameters were added as core transport parameters in IS-05 v1.2 or above it would constitute a breaking change against v1.1 (given the potential to break from the expected behaviour when supporting v1.1 and v1.2 simultaneously).

I wonder as a result whether we should add some explicit documentation for clients ahead of the v1.1 release which indicates that new transport parameters for existing defined transports might be added without a version bump. This doesn't mean that it will happen, but leaves the door open to some degree. As things stand entirely new transport type definitions would still be excluded from this.

I'd note that aside from the cases of MQTT encryption and protocol version, there are potential 'missing' parameters in the RTP transport set for encryption, and in both MQTT and WebSocket transport types for use of authentication. Being able to add these to existing transports without a version bump (and crucially without breaking existing implementations) would be desirable.

**Comment by garethsb** [comment]
Just noting that the PR that adds `api_proto` to the DNS-SD `_nmos-mqtt._tcp` service type is https://github.com/AMWA-TV/nmos-event-tally/pull/57. This currently allows `mqtt` or `secure-mqtt` (`ws` and `wss` might be allowed in the future).

So, we _could_ add `protocol` (or `scheme`, or either of those prefixed with `destination_`/`source_`) to the MQTT Sender/Receiver transport params.

If so, we should be consistent on whether a default is supported and how it is decided.
