### ISSUE TITLE
SDP files without 'source-filter'

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-device-connection-management#93]
As far as I can tell, none of the relevant SMPTE ST or IETF RFC require the `a=source-filter:` line.
JT-NM TR-1001-1:2018 Section 10.3 has:

> Media Nodes shall support IGMP V3, and shall use the source-specific method if the source address information is provided in the SDP.
> [...]
> Senders should include source address information in the SDP.

That being the case, how should a Receiver react to `PATCH /staged` with an SDP file not containing the 'source-filter' information, in both the case of a single-legged, and ST 2022-7 dual-legged, Receiver?

Not use source-specific join (`"source_ip": null`?)
Use SDP Origin (`o=`) info?
Something else?

**Comment by andrewbonney** [comment]
In my opinion we shouldn't specify that implementations make assumptions based upon the SDP origin or similar, although they're welcome to do that on a case by case basis if they wish. I would suggest that if the source-filter line is missing it should be assumed that any any-source join was intended, and the source_ip should be set to null.
